[package]
name = "rust-tomlparse"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.29.0"
clap = { version = "4.5.42", features = ["derive"] }
toml = { version = "0.9.4", features = ["preserve_order"] }
