[package]
name = "rust-tomlparse"
version = "0.1.0"
edition = "2024"

[dependencies]
calamine = "0.29.0"
clap = { version = "4.5.42", features = ["derive"] }
intelhex = "0.2.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.142", features = ["preserve_order"] }
serde_yaml = "0.9.34"
toml = { version = "0.9.4", features = ["preserve_order"] }
